// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonv0LgnweLz3Q-CKd1XbqAHHGQ8UALto',
    appId: '1:609577344516:web:2c7950b52f35d58a771f51',
    messagingSenderId: '609577344516',
    projectId: 'glicogotas-app-v2',
    authDomain: 'glicogotas-app-v2.firebaseapp.com',
    storageBucket: 'glicogotas-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3AQiq3V7F6Gnh3pXdAPk28ujUChQ9sdY',
    appId: '1:609577344516:android:b623b7d71b67010d771f51',
    messagingSenderId: '609577344516',
    projectId: 'glicogotas-app-v2',
    storageBucket: 'glicogotas-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyFv2Hm3GU6jfjwpRAHLxq-Ntysh0fs4',
    appId: '1:609577344516:ios:5f9fdfc0bf7912e1771f51',
    messagingSenderId: '609577344516',
    projectId: 'glicogotas-app-v2',
    storageBucket: 'glicogotas-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.glicogotasAppv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhyFv2Hm3GU6jfjwpRAHLxq-Ntysh0fs4',
    appId: '1:609577344516:ios:5f9fdfc0bf7912e1771f51',
    messagingSenderId: '609577344516',
    projectId: 'glicogotas-app-v2',
    storageBucket: 'glicogotas-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.glicogotasAppv2',
  );
}
